### ISSUE TITLE
A title that's not RUDE

### ISSUE THREAD

**Issue by madisonwheeler** [edude15000/game#2]
I lost a ruby when I failed to smelt a bar ☹️

**Comment by edude15000** [comment]
:)

**Comment by edude15000** [comment]
AYYYY LMAO

**Comment by Get-Hacked** [comment]
We will work on a fix for this issue. If needed, we can add a ruby to your account's inventory.

**Comment by edude15000** [comment]
user.itemList.add(new Smeltable("Ruby", 12, 1));

**Comment by edude15000** [comment]
67 business days

**Comment by Charli3theDoggo** [comment]
Did you ever think that you misplaced the ruby, not just lost it?

**Comment by madisonwheeler** [comment]
No let me check

**Comment by madisonwheeler** [comment]
It's still much lost

**Comment by edude15000** [comment]
Your bug has been fixed.

E
