### ISSUE TITLE
Raw Fish deleted upon cooking shrimp

### ISSUE THREAD

**Issue by madisonwheeler** [edude15000/game#3]
I cooked shrimp and a raw fish disappeared 😞

**Comment by Get-Hacked** [comment]
Dear madisonwheeler,

Can you provide more details about the incident? It sounds like it may be intended behavior. When you cook a fish, the raw fish is removed from your inventory, and the cooked shrimp appears at the end of the list. Is this what happened?

Signed,
Get-Hacked
Lead UI Developer
miniRPG Team

**Comment by madisonwheeler** [comment]
You will RUE the day you edited MY comment

**Comment by Get-Hacked** [comment]
Dear madisonwheeler,

Thank you for your patience in this manner. As we are a small indie company, we do not have a dedicated Customer Service branch yet. I am flattered at your reply.

We value your time and dedication to this game greatly, and thank you very much for playing. I misunderstood the situation - it appears that this is a bug. I will pass this issue along to our internal development team, and they will issue a fix soon.

If you wish, I can replace the raw fish in your inventory. Do let me know what will work best.

Sincerely,
Get-Hacked
Lead UI Developer
miniRPG Team

**Comment by madisonwheeler** [comment]
Bad company. Huge rudeness. Edited MY COMMENT to benefit their AGENDA

**Comment by Get-Hacked** [comment]
Dear user,

Sorry for any inconvenience this has caused. Be assured that we are taking steps to help you with your issue. Thank you for enjoying miniRPG. You can donate to our great game [here](google.com), or purchase the expanded edition [here](google.com).

Regards,
miniRPG

This message is not automated. We value your time and questions.

**Comment by lathaniel** [comment]
I have enjoyed my experiences with miniRPG, LLC. Great company! Minimal rudeness! They even edited my comment, as I did had many an error in it...pesky little fingers ;)

**Comment by madisonwheeler** [comment]
LIES! What kind of a company closes an issue to silence their valued customers? My fish is still gone just like my support for miniRPG 😠 😡

**Comment by Get-Hacked** [comment]
hi.
if you have issue, open new ticket.
thanks you

**Comment by lathaniel** [comment]
Hi, madisonwheeler.

Thank you for your patients. I see your ticket has been resolve. If you need any assistance farther, please download the attached text document, and then...save it as a batch (*.bat) file. Once that is properly installed, you will have our state-of-the-art Customer Service self-help application.

Should you need anything else, feel free to reach out to us at secure.customerService1234@aol.com. Note: you will need you're SSN in the subject of the email, or it will not reach our inbox :( 

[CustomerService.txt](https://github.com/edude15000/game/files/1217918/CustomerService.txt)
